package com.empData.model;

import jakarta.persistence.*;

/**
 * Represents an Employee entity mapped to the "Employee" table in the database.
 * Contains employee details such as ID, name, designation, and city.
 */
@Entity
@Table(name = "Employee")
public class Employee {

    /**
     * Unique identifier for the employee.
     * This is the primary key and is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "EmpID")
    private Long empId;

    /**
     * Name of the employee.
     */
    @Column(name = "EmpName")
    private String empName;

    /**
     * Designation or job title of the employee.
     */
    @Column(name = "EmpDesignation")
    private String empDesignation;

    /**
     * City where the employee is located.
     */
    @Column(name = "EmpCity")
    private String empCity;


    // ======== Constructors for Employee Class ========
    /**
     * Default constructor for Employee.
     * Creates an empty Employee object.
     */
    public Employee() {
    }

    /**
     * Parameterized constructor for Employee.
     * Initializes an Employee object with the specified name, designation, and city.
     *
     * @param empName the name of the employee
     * @param empDesignation the designation of the employee
     * @param empCity the city where the employee is located
     */
    public Employee(String empName, String empDesignation, String empCity) {
        this.empName = empName;
        this.empDesignation = empDesignation;
        this.empCity = empCity;
    }

    // ======== Getters and Setters for Employee Fields ========

    /**
     * Gets the employee ID.
     *
     * @return the employee ID
     */
    public Long getEmpId(){
        return empId;
    }

    /**
     * Sets the employee ID.
     *
     * @param empId the employee ID to set
     */
    public void setEmpId(Long empId){
        this.empId = empId;
    }

    /**
     * Gets the employee name.
     *
     * @return the employee name
     */
    public String getEmpName(){
        return empName;
    }

    /**
     * Sets the employee name.
     *
     * @param empName the employee name to set
     */
    public void setEmpName(String empName){
        this.empName = empName;
    }

    /**
     * Gets the employee designation.
     *
     * @return the employee designation
     */
    public String getEmpDesignation(){
        return this.empDesignation;
    }

    /**
     * Sets the employee designation.
     *
     * @param empDesignation the employee designation to set
     */
    public void setEmpDesignation(String empDesignation){
        this.empDesignation = empDesignation;
    }

    /**
     * Gets the employee city.
     *
     * @return the employee city
     */
    public String getEmpCity(){
        return this.empCity;
    }

    /**
     * Sets the employee city.
     *
     * @param empCity the employee city to set
     */
    public void setEmpCity(String empCity){
        this.empCity = empCity;
    }

    /**
     * Returns a string representation of the Employee object.
     * Includes employee ID, name, designation, and city in a readable format.
     *
     * @return a string describing the employee
     */
    @Override
    public String toString(){
        return "Employee [Employee ID : "+empId+", Employee Name : "+empName+", Employee Designation : "+empDesignation+", Employee City : "+empCity;
    }


}
